In [4]:
import numpy as np


In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=6)
print(a)
print(a[0,0,0,0,0])
              
              

[[[[[[ 1  2  3  4  5]
     [ 6  7  8  9 10]]]]]]
[1 2 3 4 5]


In [3]:
a = np.array([[1,2,3,4],[6,7,8,9]],ndmin=4)
print(a[0,0,0,1:2],a[0,0,1,1:2])

[2] [7]


In [4]:
a = np.array([[1,2,3,4],[6,7,8,9]],ndmin=4)
print(a[0,0,0])


[1 2 3 4]


In [5]:
a= np.arrange(1,8)


print(a)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
a= np.array([[1,2,3,4],[9,10,11,12]])
b = np.array([[5,6,7,8],[13,14,15,16]])
c = np.concatenate((a,b),axis =1)
print(c)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [7]:
x =np.array([2,1,5,7,0,4,3j,"abc"])
print(x)


['2' '1' '5' '7' '0' '4' '3j' 'abc']


In [8]:
x = np.array([[[[[1,2,3,4,5]]]]])
print(x.ndim)

5


In [9]:
x = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]]]]])
print(x.shape)

(1, 1, 1, 2, 5)


In [10]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
z = np.array([[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]])
print(y)
print(z)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [11]:
x= np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])
print(x.size)

15


In [12]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y =x.transpose()
print(y)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
x=np.full((4,3),12)
y= x+4
z = y*3
print(z)


[[48 48 48]
 [48 48 48]
 [48 48 48]
 [48 48 48]]


In [14]:
x= np.zeros((5,6))
print(x)
y = x+10
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]
